sudo: false

language: python

python: "3.5.6"

services:
    - postgresql

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
    - $HOME/.pyenv_cache

env:
  global:
    - DATABASE_URL=postgres://localhost/serializationspec
    - SECRET_KEY=sekrit

before_install:
  - |
    wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
    source setup-pyenv.sh

install:
  - ./build.sh

before_script:
  - psql -c 'create database serializationspec;' -U postgres

script: ./runtests
