#!/usr/bin/env bash

set -e

export PATH=env/bin:${PATH}
export DEBUG=true
export IN_TEST=true
export DEFAULT_FILE_STORAGE='storages.backends.s3boto3.S3Boto3Storage'

sh -c '! ./manage.py makemigrations --dry-run --exit' # fail if makemigrations hasn't been run

echo "--------------"
echo "Running python type checking"
mypy --ignore-missing-imports --follow-imports=skip --strict-optional  --warn-no-return project
echo "Ok!"

echo "--------------"
echo "Running Flake8 linting"
flake8 project --ignore=E128,E501 --exclude="migrations,settings,*/wsgi.py"
echo "Ok!"

